apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: 865749917919.dkr.ecr.us-east-1.amazonaws.com/todo-backend:latest

          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql://todo:todo123@todo-postgres:5432/tododb"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"